---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: 4pd-vgpu-hook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURoRENDQW15Z0F3SUJBZ0lVUHJScUdtdDZUYUxTZGRBMGE4L3Q0V0lUemxzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1dURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFXcHBibWN4RURBT0JnTlZCQWNUQjBKbAphV3BwYm1jeEVqQVFCZ05WQkFzVENUUndZWEpoWkdsbmJURVNNQkFHQTFVRUF4TUpjR2x1WldGd2NHeGxNQ0FYCkRUSXhNRFV4T1RBME16Y3dNRm9ZRHpJeE1qRXdOREkxTURRek56QXdXakJaTVFzd0NRWURWUVFHRXdKRFRqRVEKTUE0R0ExVUVDQk1IUW1WcGFtbHVaekVRTUE0R0ExVUVCeE1IUW1WcGFtbHVaekVTTUJBR0ExVUVDeE1KTkhCaApjbUZrYVdkdE1SSXdFQVlEVlFRREV3bHdhVzVsWVhCd2JHVXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCCkR3QXdnZ0VLQW9JQkFRREIxQkZKdVJUSzRGN2pGa3BSbGRhZFI2Z3QwaVZTVnNHN2NlMWwvYjFWUXV1bm1uSGQKNTUzOFRmR3YwTHlUTG5QZXVEVnRXNXljZzVlYnpqZXlUMHZZbWV2SEl0UmFnOU4rWFNQTUQrK2hIT3VhTVR2OQo5dDNGZDJVZ1FRTmtzc09KTjVBNEs3SWsxWWFzTVNIV2RsUTNuOUlNVGFLOWQ1V29PYlA0MzVKVEh5WHV3UHZlCjI3QW5kdFcvTXkxVEd3bHZ1QXRienFUd2l1Wk1acnBJamxFei9lNytMVVZZWnoyb2RPUzQ2QXF3eS81SVhMYnYKZkIweitDUFVjNmkzNjhGYlI3cHF1TEowVkxEd3ZHeEhWMFhhc09wdWNGNUtvUTMvNFB0R2FtSHZGTUk2TkpIbQpVbkhYWUt5d3ZSSUpZdXpnMnh3clQ0STVrYVJwQVBOZ0o2V1RBZ01CQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFCkF3SUJCakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlJNeGJDdHUvTUJ6YitPbmhHZEs1SlcKSkV1cXd6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFQMEtJb01KcHRjK256NXh6K3hWalRPbWtmSUpNdFhoWgo3SHJTL05EaFAwNjl0UmZOZVNtcFRaSVdkTUUwUDd6TnRka0R0Y2xwdmhEWEF4RHpuVXowRHg3K0EySnNKRGcyCmxyb3Arczh1WG8rNDRsdzRwMEtEeHRTWGFxQS9VREpxRjhYVUFyeE96SHBPY2t3clFBS2JJRXh0WDNDVjBta0EKUUwrdXBKSS9BOG43ZVg0VXRhZ1pBWWlKUmVPZ3dWTXpTWU1KQ3E5b0IvNUg4NVJlQTZlVEJqV0Noa1VrVTdpWgpwQWprUGpQUWp0TG9SUU8vVmorOGpneEJ5VDlVMXR0cUViV3RLOW5QUTFzcFRNMkNoSEwxSkpoN3pyNEZKV2xRCldCeGdaYlRwbS9sSGZUTk96MjlIM3k0QmpvUXdOMmNOR3VlcmsrVWwwYVlHcCtyK0RIejVlZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
#    service:
#      name: 4pd-vgpu-scheduler
#      namespace: vgpu
#      path: /webhook
#      port: 443
    url: https://172.27.95.15:3456/webhook
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: vgpu.4pd.io
#  namespaceSelector:
#    matchExpressions:
#    - key: 4pd.io/webhook
#      operator: NotIn
#      values:
#      - ignore
#  objectSelector:
#    matchExpressions:
#    - key: 4pd.io/webhook
#      operator: NotIn
#      values:
#      - ignore
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
