{{- $cn := printf "%s.%s.svc" ( include "4pd-vgpu.scheduler" . ) .Release.Namespace -}}
{{- $ca := genCA $cn 3650 -}}
{{- $cert := genSignedCert $cn (list "127.0.0.1") (list $cn) 3650 $ca -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: 4pd-vgpu-hook
webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      caBundle: {{ b64enc $ca.Cert }}
      service:
        name: {{ include "4pd-vgpu.scheduler" . }}
        namespace: {{ .Release.Namespace }}
        path: /webhook
        port: {{ .Values.scheduler.service.httpPort }}
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: vgpu.4pd.io
    namespaceSelector:
      matchExpressions:
      - key: 4pd.io/webhook
        operator: NotIn
        values:
        - ignore
    objectSelector:
      matchExpressions:
      - key: 4pd.io/webhook
        operator: NotIn
        values:
        - ignore
    reinvocationPolicy: Never
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "4pd-vgpu.scheduler.tls" . }}
  labels: {{- include "4pd-vgpu.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
  ca.crt: {{ b64enc $ca.Cert }}
