apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "hami-vgpu.scheduler.webhook" . }}
webhooks:
  - admissionReviewVersions:
    - v1beta1
    clientConfig:
      {{- if .Values.scheduler.webhook.customURL.enabled }}
      url: https://{{ .Values.scheduler.webhook.customURL.host}}:{{.Values.scheduler.webhook.customURL.port}}{{.Values.scheduler.webhook.customURL.path}}
      {{- else }}
      service:
        name: {{ include "hami-vgpu.scheduler" . }}
        namespace: {{ .Release.Namespace }}
        path: /webhook
        port: {{ .Values.scheduler.service.httpPort }}
      {{- end }}
    failurePolicy: {{ .Values.scheduler.mutatingWebhookConfiguration.failurePolicy }}
    matchPolicy: Equivalent
    name: vgpu.hami.io
    namespaceSelector:
      matchExpressions:
      - key: hami.io/webhook
        operator: NotIn
        values:
        - ignore
      {{- if .Values.scheduler.webhook.whitelistNamespaces }}
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        {{- toYaml .Values.scheduler.webhook.whitelistNamespaces | nindent 10 }}
      {{- end }}
    objectSelector:
      matchExpressions:
      - key: hami.io/webhook
        operator: NotIn
        values:
        - ignore
    reinvocationPolicy: {{ .Values.scheduler.webhook.reinvocationPolicy }}
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
        scope: '*'
    sideEffects: None
    timeoutSeconds: 10
